---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1m7a7kjfryulhud63g9j8l6ng292axswhd6vg4wguawxecpwppqfqgvcedm
  - path_regex: kubernetes/.*\.sops\.(env|ini|json|toml)
    key_groups:
      - age:
          - age1m7a7kjfryulhud63g9j8l6ng292axswhd6vg4wguawxecpwppqfqgvcedm
  - path_regex: terraform/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1m7a7kjfryulhud63g9j8l6ng292axswhd6vg4wguawxecpwppqfqgvcedm
  - path_regex: infrastructure/nix/secrets/.*\.sops\.ya?ml$
    key_groups:
      - age:
          - age1m7a7kjfryulhud63g9j8l6ng292axswhd6vg4wguawxecpwppqfqgvcedm
