---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich-web
  namespace: selfhosted
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  dependsOn:
    - name: immich-server

  values:
    controllers:
      main:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          enableServiceLinks: false
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 65541

        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-web
              tag: v1.83.0
            command:
              - /bin/sh
            args:
              - ./entrypoint.sh
            env:
              # Ports
              PORT: &port 3000
              # URLs
              IMMICH_SERVER_URL:
                valueFrom:
                  configMapKeyRef:
                    name: immich-configmap
                    key: IMMICH_SERVER_URL
              PUBLIC_IMMICH_SERVER_URL:
                valueFrom:
                  configMapKeyRef:
                    name: immich-configmap
                    key: PUBLIC_IMMICH_SERVER_URL
              IMMICH_API_URL_EXTERNAL: /api
            resources:
              requests:
                cpu: 5m
                memory: 64M
              limits:
                memory: 256Mi

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        className: "external-nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress-ext.monosense.io
          nginx.ingress.kubernetes.io/configuration-snippet: |
            rewrite /api/(.*) /$1 break;
            set $forwarded_client_ip "";
            if ($http_x_forwarded_for ~ "^([^,]+)") {
              set $forwarded_client_ip $1;
            }
            set $client_ip $remote_addr;
            if ($forwarded_client_ip != "") {
              set $client_ip $forwarded_client_ip;
            }
          nignx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          nginx.ingress.kubernetes.io/upstream-hash-by: "$client_ip"
        hosts:
          - host: &host photo.monosense.io
            paths:
              - path: /
                service:
                  name: main
                  port: http
              - path: /api
                service:
                  name: immich-server
                  port: 3001
        tls:
          - hosts:
              - *host