---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-configmap
  namespace: selfhosted
data:
  # URLS
  IMMICH_WEB_URL: http://immich-web.selfhosted.svc.cluster.local:3000
  IMMICH_SERVER_URL: http://immich-server.selfhosted.svc.cluster.local:3001
  PUBLIC_IMMICH_SERVER_URL: https://photo.monosense.io

  # REDIS
  REDIS_HOSTNAME: immich-redis.selfhosted.svc.cluster.local
  REDIS_PORT: "6379"

  # TYPESENSE
  TYPESENSE_ENABLED: "true"
  TYPESENSE_HOST: immich-typesense.selfhosted.svc.cluster.local
  TYPESENSE_PORT: "8108"
  TYPESENSE_PROTOCOL: http