---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich-server
  namespace: selfhosted
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  dependsOn:
    - name: immich-typesense

  values:
    controllers:
      main:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          enableServiceLinks: false
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 65542 # gladius:external-services
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: immich-server

        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.83.0
            args:
              - start-server.sh
            env:
              # General
              LOG_LEVEL: log
              IMMICH_CONFIG_FILE: /config/immich.config.json
              IMMICH_MEDIA_LOCATION: &mediaLocation /usr/src/app/upload
              # Ports
              SERVER_PORT: &port 3001
              # Database
              DB_HOSTNAME:
                valueFrom:
                  secretKeyRef:
                    name: immich-pguser-immich
                    key: host
              DB_PORT: 5432
              DB_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: immich-pguser-immich
                    key: user
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: immich-pguser-immich
                    key: password
              DB_DATABASE_NAME:
                valueFrom:
                  secretKeyRef:
                    name: immich-pguser-immich
                    key: dbname
              # Redis
              REDIS_HOSTNAME:
                valueFrom:
                  configMapKeyRef:
                    name: immich-configmap
                    key: REDIS_HOSTNAME
              REDIS_PORT:
                valueFrom:
                  configMapKeyRef:
                    name: immich-configmap
                    key: REDIS_PORT
              # Typesense
              TYPESENSE_ENABLED:
                valueFrom:
                  configMapKeyRef:
                    name: immich-configmap
                    key: TYPESENSE_ENABLED
              TYPESENSE_API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: immich-secret
                    key: TYPESENSE_API_KEY
              TYPESENSE_HOST:
                valueFrom:
                  configMapKeyRef:
                    name: immich-configmap
                    key: TYPESENSE_HOST
              TYPESENSE_PORT:
                valueFrom:
                  configMapKeyRef:
                    name: immich-configmap
                    key: TYPESENSE_PORT
              TYPESENSE_PROTOCOL:
                valueFrom:
                  configMapKeyRef:
                    name: immich-configmap
                    key: TYPESENSE_PROTOCOL
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 512Mi

    service:
      main:
        ports:
          http:
            port: *port

    persistence:
      config:
        enabled: true
        type: secret
        name: immich-config-secret
        globalMounts:
          - path: /config
      library:
        type: persistentVolumeClaim
        existingClaim: immich-nfs
        globalMounts:
          - path: *mediaLocation