---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: arc-assets
  namespace: dev
spec:
  interval: 30m
  chart:
    spec:
      chart: actions-runner-controller-charts/gha-runner-scale-set
      version: 0.6.1
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
      interval: 30m

  values:
    runnerScaleSetName: arc-runner-set-assets

    githubConfigUrl: https://github.com/monosense25/assets

    minRunners: 0
    maxRunners: 2

    containerMode:
      type: "dind"

    template:
      spec:
        containers:
          - name: runner
            image: ghcr.io/actions/actions-runner:2.311.0@sha256:08e29186e7cadd698afeb228e90e8a1fd2262b0ad48022ef731e799f80b6be16

  valuesFrom:
    - kind: Secret
      name: actions-runner-controller-auth
      valuesKey: github_app_id
      targetPath: githubConfigSecret.github_app_id
    - kind: Secret
      name: actions-runner-controller-auth
      valuesKey: github_app_installation_id
      targetPath: githubConfigSecret.github_app_installation_id
    - kind: Secret
      name: actions-runner-controller-auth
      valuesKey: github_app_private_key
      targetPath: githubConfigSecret.github_app_private_key
