---
apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-gatus-ep
  namespace: home
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: home-assistant
        group: external
        url: https://hass.monosense.io
        interval: 1m
        client:
          dns-resolver: tcp://172.16.14.5:53
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: pushover