---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflared-tunnel
  namespace: network
spec:
  endpoints:
    - dnsName: ingress-ext.monosense.io
      recordType: CNAME
      targets: ["4bfe213a-d05d-4bab-a568-784d4d9be4dd.cfargotunnel.com"]