---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ./helmrelease.yaml
  - ./bgppeeringpolicy.yaml
  - ./l2announcementpolicy.yaml
configMapGenerator:
  - name: cilium-values
    files:
      - values.yaml=./values.yaml
generatorOptions:
  disableNameSuffixHash: true

configurations:
  - kustomizeconfig.yaml
